### ISSUE TITLE
Extend documentation for nxt-sortablejs

### ISSUE THREAD

**Issue by mc-paula** [Liquid-JS/nxt-components#1]
Maybe you can extend the documentation of nxt-sortablejs to explain how to use the options property. I imagine something like this in the README https://github.com/Liquid-JS/nxt-components/tree/master/packages/sortablejs#readme:
This will make the migration from ngx-sortablejs way easier 😃 

### Passing the options

Pass the options with `config` property.

```typescript
import { Component } from "@angular/core";

@Component({
  selector: "my-app",
  template: `
    <h2>Drag / drop the item</h2>
    <div [nxtSortablejs]="items" [config]="options">
      <div *ngFor="let item of items">{{ item }}</div>
    </div>
  `,
})
export class AppComponent {
  items = [1, 2, 3, 4, 5];

  options = {
    onUpdate: (event: any) => {
      this.postChangesToServer();
    },
  };
}
```

**Comment by HitkoDev** [comment]
There are several examples on the [Demo page](https://liquid-js.github.io/nxt-components/demo/sortablejs). If there are any general use cases not covered by the demo examples, feel free to reopen this issue and recommend them.
