### ISSUE TITLE
Objects don't fire onUpdate event when moving between lists

### ISSUE THREAD

**Issue by RGerhardt-Pressmind** [Liquid-JS/nxt-components#2]
Hello,

I have grouped my elements. So nested and then used the "group" option to further sort them among each other. Unfortunately it does not fire an "onUpdate" event when I change the hierarchy of the elements. If I stay on the same hierarchy it fires the "onUpdate" event normally.

Do you need an example or do you understand what I mean? :)

Thanks a lot.

```javascript
sortableModuleOptions   =   {
    	group: 'test',
		onUpdate: (event: any) => {
			console.log('Update module');
			this.saveModulePosition();
		},
		chosenClass: 'chosenModul'
	};
``` 

```javascript
allElements	=	[
		{
			title: 'Test 1',
			childs: [
				{
					title: 'Test 1.1'
				},
				{
					title: 'Test 1.2'
				},
				{
					title: 'Test 1.3'
				}
			]
		},
		{
			title: 'Test 2'
		}
	];
```

**Comment by HitkoDev** [comment]
This doesn't seem to be a problem with `nxt-storablejs`. As per SortableJS documentation, the `onUpdate` event only triggers when reordering items within the same list, not within the same group (see https://github.com/SortableJS/Sortable#options). To catch other events, you have to listen for `onAdd` / `onRemove` events.

StackBlitz example: https://stackblitz.com/edit/angular-xgodsf?file=src%2Fmain.ts
