### ISSUE TITLE
Localize "Set" and "Cancel" in Datetime Picker

### ISSUE THREAD

**Issue by ontec-xrail** [Liquid-JS/nxt-components#5]
Hi, 

probably a stupid question but how can I localize the two strings "Set" and "Cancel" 

I couldn't find a example in the documentation? Could you help me out?

![image](https://github.com/user-attachments/assets/dfd8f36e-4ef8-4571-82e0-1b93b116ad1c)

Thanks Max

**Comment by HitkoDev** [comment]
The components use [@angular/localize](https://angular.dev/guide/i18n).

If you run `ng extract-i18n`, you'll see `nxt-pick-datetime.cancel` and `nxt-pick-datetime.set` in your output file, and you can change these values just like any other localised string. If you don't wish to use `@angular/localize`, you can also override the [DateTimeIntl](https://github.com/Liquid-JS/nxt-components/blob/master/packages/pick-datetime/src/lib/date-time/date-time-picker-intl.service.ts) service to provide localised values.
