### ISSUE TITLE
[sortablejs] Slow when 300+ items

### ISSUE THREAD

**Issue by spider9375** [Liquid-JS/nxt-components#6]
I have a list of 300+ rows and dragging is really slow. On 2nd drag my work machine starts fans on max and website almost freezes. I read in stackoverflow that a potential fix is to disable changeDetection. What i have done is 

```
        onStart: (e) => {
            e.preventDefault();
            this.cd.detach();
        },
        onEnd: (e) => {
            e.preventDefault();
            this.cd.reattach();
        },
        onUpdate: (e) => {
            this.games.splice(e.newIndex, 0, this.games.splice(e.oldIndex, 1)[0]);
            this.orderChanged.emit(sortByPinned(this.games))
        }
```

however the issue persists. Do you have any suggestions ?

**Comment by HitkoDev** [comment]
Please see https://github.com/Liquid-JS/nxt-components/tree/master/packages/demo/src/app/sortablejs/examples/scrolling-options for an example of how to improve performance with long lists.

**Comment by spider9375** [comment]
In your example you work with 30 items. Is 30 considered a lot? Im dealing with 400+ and this does not work for me. First drag n drop is instant and next ones are slow and put cpu and ram at 99%

**Comment by HitkoDev** [comment]
[Here](https://stackblitz.com/edit/stackblitz-starters-mitk1b?file=src%2Fmain.ts) is the same example with 500 items; it should work smoothly even after reordering the items several times. I recommend to use that example as a starting point for your sortable list component.
