### ISSUE TITLE
Discrepancy Between Visual Order and Data Model in Drag-and-Drop Demo with Object-Based List

### ISSUE THREAD

**Issue by fyan0125** [Liquid-JS/nxt-components#7]
![螢幕擷取畫面 2024-12-09 155836](https://github.com/user-attachments/assets/9843d663-6b7f-4395-8c66-3ed489463b50)
This screenshot is from the demo website. When the list items are objects (as shown in the example where each item has properties like draggable and text), the actual result does not match the displayed order on the screen after dragging operations.

For example, even if the displayed order changes after rearranging the elements, the underlying data model (draggableItems) does not reflect the updated order. This causes discrepancies between the visual order in the UI and the actual list model in the code.

**Comment by HitkoDev** [comment]
It seems the issue was related to lists with disabled items. Should be fixed in `19.0.1`.
