### ISSUE TITLE
sortablejs : sortablejsContainer not working with mat-table and other late rendered containers

### ISSUE THREAD

**Issue by marcfal** [Liquid-JS/nxt-components#8]
Hi,

I'm using this package to allow sorting of rows in a mat-table.
If I set sortablejsContainer="tbody", I get the error 
> Sortable: `el` must be an HTMLElement, not [object Null]

I managed to work around the issue by moving this line : 
https://github.com/Liquid-JS/nxt-components/blob/c4bb747b4352b05012c2faec0330f0898c8d2761/packages/sortablejs/src/lib/sortablejs.directive.ts#L100

To inside the setTimeout() callback.

Although not an ideal solution, it's a minimal change that should make the directive more resilient to these kind of late rendered containers.

EDIT : I'm using Angular 18

**Comment by HitkoDev** [comment]
Please see https://liquid-js.github.io/nxt-components/demo/sortablejs/#example-9
